version: "3.9"

services:
  db:
    build:
      context: .
      dockerfile: DockerfileDb
    image: gcanonf/gcanon_mariadb:11-typo3-init   
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: db
      MYSQL_PASSWORD: db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - typo3    

  web:
    build:
      context: .
      dockerfile: DockerfileTypo3
    restart: always
    depends_on:
      - db
    environment:
      TYPO3_CONTEXT: Production
    volumes:
      - fileadmin:/var/www/html/public/fileadmin
      - systemconf:/var/www/html/config/system
      - var_data:/var/www/html/var
    networks:
      - typo3

networks:
  typo3:

volumes:
  db_data:
  fileadmin:
  systemconf:
  var_data: